#!/bin/sh -e

# Enable debugging
if [ ! -z "$DEBUG" ]; then
    set -x
fi

# Set up environment
. docker-project-init.sh
. docker-apache-init.sh

## install project
if [ -n "$PROJECT_VCS_URL" ]; then
    git clone -b "$PROJECT_VCS_BRANCH" "$PROJECT_VCS_URL" "./$PROJECT_APPDIR"
    chown -R $APACHE_RUN_USER:$APACHE_RUN_GROUP "./$PROJECT_APPDIR"
fi

if [ -f ~/.ssh/config ]; then
    sed -i "s/StrictHostKeyChecking no/StrictHostKeyChecking yes/"  ~/.ssh/config
fi

exec "$@"
