#!/bin/sh -e

# Enable debugging
if [ ! -z "$DEBUG" ]; then
    set -x
fi

# Set up environment
. project-init
. apache-init

## install project
if [ -n "$PROJECT_VCS_URL" ]; then
    cd "$PROJECT_WORKDIR"
    git clone -b "$PROJECT_VCS_BRANCH" "$PROJECT_VCS_URL" "./$PROJECT_APPDIR"
    chown -R $APACHE_RUN_USER:$APACHE_RUN_GROUP "./$PROJECT_APPDIR"
    cd "./$PROJECT_APPDIR"
    if [ -f composer.json ]; then
        composer update
    fi
fi

exec entrypoint "$@"
